import os
from unittest import TestCase, skipIf

from conftest import EMPTY_CRC, OTHER_PAYLOAD, OTHER_PAYLOAD_CRC, PAYLOAD_CRC, TempDirTestCase

from autocrc import core
from autocrc.core import CrcResult, Options, Status, Summary


class CrcFromFilenameTest(TestCase):
    def test_supported_delimiters(self):
        test_data = [
            ("video [1f2e3d4c].mkv", "1F2E3D4C"),
            ("video (1F2E3D4C).mkv", "1F2E3D4C"),
            ("video_1F2E3D4C_.mkv", "1F2E3D4C"),
        ]

        for file_name, expected in test_data:
            with self.subTest(file_name=file_name):
                self.assertEqual(expected, core.crc_from_filename(file_name))

    def test_no_crc(self):
        test_data = [
            "video.mkv",
            "video [1F2E3D4].mkv",  # too short
            "video [1F2E3D4C5].mkv",  # too long
            "video [ZZZZZZZZ].mkv",  # not hexadecimal
        ]

        for file_name in test_data:
            with self.subTest(file_name=file_name):
                self.assertIsNone(core.crc_from_filename(file_name))


class ParseSfvLineTest(TestCase):
    def test_parses_name_and_crc(self):
        self.assertEqual(("video.mkv", "1F2E3D4C"), core.parse_sfv_line("video.mkv 1f2e3d4c\n"))

    def test_ignores_comments(self):
        self.assertIsNone(core.parse_sfv_line("; generated by pure-sfv\n"))

    def test_ignores_garbage(self):
        self.assertIsNone(core.parse_sfv_line("not an sfv line\n"))

    def test_keeps_backslashes_by_default(self):
        self.assertEqual(("dir\\video.mkv", "1F2E3D4C"), core.parse_sfv_line("dir\\video.mkv 1F2E3D4C\n"))

    def test_exchange_rewrites_backslashes(self):
        self.assertEqual(
            ("dir/video.mkv", "1F2E3D4C"),
            core.parse_sfv_line("dir\\video.mkv 1F2E3D4C\n", exchange=True),
        )


class Crc32OfFileTest(TempDirTestCase):
    def test_known_crc(self):
        path = self.write_file("payload.bin")
        self.assertEqual(PAYLOAD_CRC, core.crc32_of_file(path))

    def test_block_size_does_not_affect_result(self):
        path = self.write_file("payload.bin", b"x" * 100000)
        self.assertEqual(core.crc32_of_file(path, block_size=8192), core.crc32_of_file(path, block_size=7))

    def test_empty_file(self):
        path = self.write_file("empty.bin", b"")
        self.assertEqual(EMPTY_CRC, core.crc32_of_file(path))

    def test_read_only_file(self):
        """Regression test: files used to be opened with 'r+', which needs write permission."""
        path = self.write_file("payload.bin", mode=0o444)
        self.assertEqual(PAYLOAD_CRC, core.crc32_of_file(path))

    def test_missing_file(self):
        with self.assertRaises(FileNotFoundError):
            core.crc32_of_file(self.path("nope.bin"))


class CrcsInDirTest(TempDirTestCase):
    def test_crc_from_filename(self):
        self.write_file(f"video [{PAYLOAD_CRC}].mkv")
        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options())
        self.assertEqual({f"video [{PAYLOAD_CRC}].mkv": PAYLOAD_CRC}, crcs)

    def test_crc_from_sfv(self):
        self.write_file("payload.bin")
        self.write_sfv("check.sfv", ["; a comment", f"payload.bin {PAYLOAD_CRC}"])

        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options())
        self.assertEqual({"payload.bin": PAYLOAD_CRC}, crcs)

    def test_no_sfv_skips_sfv_files(self):
        self.write_file("payload.bin")
        self.write_sfv("check.sfv", [f"payload.bin {PAYLOAD_CRC}"])

        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options(sfv=False))
        self.assertEqual({}, crcs)

    def test_no_crc_skips_file_names(self):
        self.write_file(f"video [{PAYLOAD_CRC}].mkv")
        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options(crc=False))
        self.assertEqual({}, crcs)

    def test_directories_are_ignored(self):
        os.mkdir(self.path(f"dir [{PAYLOAD_CRC}]"))
        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options())
        self.assertEqual({}, crcs)

    def test_case_sensitive_by_default(self):
        self.write_file("Payload.bin")
        self.write_sfv("check.sfv", [f"payload.bin {PAYLOAD_CRC}"])

        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options())
        self.assertEqual({"payload.bin": PAYLOAD_CRC}, crcs)

    def test_ignore_case_resolves_real_name(self):
        self.write_file("Payload.bin")
        self.write_sfv("check.sfv", [f"payload.BIN {PAYLOAD_CRC}"])

        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options(case=False))
        self.assertEqual({"Payload.bin": PAYLOAD_CRC}, crcs)

    def test_ignore_case_resolves_names_with_directories(self):
        """Regression test: --ignore-case used to only match basenames."""
        self.write_file("SubDir/Payload.bin")
        self.write_sfv("check.sfv", [f"subdir/payload.bin {PAYLOAD_CRC}"])

        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options(case=False))
        self.assertEqual({"SubDir/Payload.bin": PAYLOAD_CRC}, crcs)

    def test_ignore_case_keeps_name_when_nothing_matches(self):
        self.write_sfv("check.sfv", [f"absent.bin {PAYLOAD_CRC}"])

        crcs = core.crcs_in_dir(self.temp_dir, os.listdir(self.temp_dir), Options(case=False))
        self.assertEqual({"absent.bin": PAYLOAD_CRC}, crcs)


class CheckDirTest(TempDirTestCase):
    def test_all_statuses(self):
        self.write_file("ok.bin")
        self.write_file("bad.bin", OTHER_PAYLOAD)
        self.write_sfv(
            "check.sfv",
            [
                f"ok.bin {PAYLOAD_CRC}",
                f"bad.bin {PAYLOAD_CRC}",
                f"gone.bin {PAYLOAD_CRC}",
            ],
        )

        results = core.check_dir(self.temp_dir, os.listdir(self.temp_dir), Options())
        by_name = {result.name: result for result in results}

        self.assertEqual(Status.OK, by_name["ok.bin"].status)
        self.assertEqual(Status.MISMATCH, by_name["bad.bin"].status)
        self.assertEqual(OTHER_PAYLOAD_CRC, by_name["bad.bin"].actual)
        self.assertEqual(Status.MISSING, by_name["gone.bin"].status)
        self.assertIsNone(by_name["gone.bin"].actual)

    @skipIf(os.geteuid() == 0, "root bypasses file permissions")
    def test_unreadable_file_is_a_read_error(self):
        self.write_file("unreadable.bin", mode=0o000)
        self.write_sfv("check.sfv", [f"unreadable.bin {PAYLOAD_CRC}"])

        results = core.check_dir(self.temp_dir, os.listdir(self.temp_dir), Options())
        self.assertEqual([Status.READ_ERROR], [result.status for result in results])

    def test_results_are_sorted_by_name(self):
        for name in ["c.bin", "a.bin", "b.bin"]:
            self.write_file(name)
        self.write_sfv("check.sfv", [f"{name} {PAYLOAD_CRC}" for name in ["c.bin", "a.bin", "b.bin"]])

        results = core.check_dir(self.temp_dir, os.listdir(self.temp_dir), Options())
        self.assertEqual(["a.bin", "b.bin", "c.bin"], [result.name for result in results])

    def test_no_crcs_gives_no_results(self):
        self.write_file("payload.bin")
        self.assertEqual([], core.check_dir(self.temp_dir, os.listdir(self.temp_dir), Options()))


class WalkTargetsTest(TempDirTestCase):
    def test_files_are_grouped_by_directory(self):
        self.write_file("a/one.bin")
        self.write_file("a/two.bin")
        self.write_file("b/three.bin")

        targets = dict(
            core.walk_targets(
                [self.path("a", "one.bin"), self.path("a", "two.bin"), self.path("b", "three.bin")],
                [],
                Options(),
            )
        )

        self.assertEqual({self.path("a"): ["one.bin", "two.bin"], self.path("b"): ["three.bin"]}, targets)

    def test_non_recursive_lists_only_the_directory(self):
        self.write_file("top.bin")
        self.write_file("sub/nested.bin")

        targets = dict(core.walk_targets([], [self.temp_dir], Options()))
        self.assertEqual([self.temp_dir], list(targets))
        self.assertEqual({"top.bin", "sub"}, set(targets[self.temp_dir]))

    def test_recursive_descends_into_subdirectories(self):
        self.write_file("top.bin")
        self.write_file("sub/nested.bin")

        targets = dict(core.walk_targets([], [self.temp_dir], Options(recursive=True)))
        self.assertEqual({self.temp_dir: ["top.bin"], self.path("sub"): ["nested.bin"]}, targets)


class SummaryTest(TestCase):
    def test_from_results_counts_statuses(self):
        results = [
            CrcResult("a", "1", "1", Status.OK),
            CrcResult("b", "1", "2", Status.MISMATCH),
            CrcResult("c", "1", None, Status.MISSING),
            CrcResult("d", "1", None, Status.READ_ERROR),
        ]

        summary = Summary.from_results(results)

        self.assertEqual(
            Summary(nr_files=4, nr_successful=1, nr_different=1, nr_missing=1, nr_read_errors=1, nr_dirs=1),
            summary,
        )

    def test_add_accumulates_across_directories(self):
        first = Summary(nr_files=2, nr_successful=2, nr_dirs=1)
        second = Summary(nr_files=1, nr_missing=1, nr_dirs=1)

        self.assertEqual(Summary(nr_files=3, nr_successful=2, nr_missing=1, nr_dirs=2), first + second)

    def test_everything_ok(self):
        self.assertTrue(Summary(nr_files=3, nr_successful=3).everything_ok)
        self.assertFalse(Summary(nr_files=3, nr_different=1).everything_ok)
        self.assertFalse(Summary(nr_files=3, nr_missing=1).everything_ok)
        self.assertFalse(Summary(nr_files=3, nr_read_errors=1).everything_ok)
